extends Node

var ALL_ITEMS = {
  0: {
    "name": "Hairpin 1",
    "desc": "Blah blah"
  },
  1: {
    "name": "Briefs",
    "desc": "Blah blah"
  },
}

func use_item_by_index(index: int) -> void:
  pass
  
func use_item_by_name(name: String) -> void:
  # get the item
  # call its members
  # signal use of item
  pass

func get_item(index, name) -> void:
  print ("Pretending to get item")
  pass
  #return Item(ALL_ITEMS[0])

func view_inventory()-> void:
  pass
  
func _ready() -> void:
  pass # Replace with function body.

func _process(delta: float) -> void:
  pass
