extends Node3D

@export var spine_item_name: String = "item_1" 
@onready var spine_sprite: SpineSprite = $MeshInstance3D/SubViewport/SpineSprite

func _ready() -> void:
  var s = spine_sprite.get_skeleton()
  var attachment = s.get_attachment_by_slot_name("item_1", spine_item_name)
  var slot = s.find_slot("item_1")
  slot.set_attachment(attachment)

func drop() -> void:
  #enable physics
  #random angle throw
  #signal item dropped
  pass

func use() -> void:
  #call item interface
  #signal item dropped
  pass
  
func pick_up() -> void:
  #signal item picked up for cutscene manager
  #insert item into inventory
  pass

func _process(delta: float) -> void:
  pass
